# This file contains values from Cookiecutter

default_context:
  project_name: "medulla"
  project_description: "Toolkit empowering Language Models (LLMs) to seamlessly interact with external APIs and tools."
  organization: "Utkarsh Kanwat"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "Medulla-ML"
  email: "utkarshkanwat@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
